# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gram', '0002_auto_20180514_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['image']},
        ),
    ]
